In [108]:
import pandas as pd

In [109]:
df = pd.DataFrame()
df = pd.read_csv('./data/weather.csv')

# How does the data look?
print(df)

                     DT  YEAR  M  D   H  WSP   HS
0   1957-09-01 06:00:00  1957  9  1   6  8.9  0.5
1   1957-09-01 09:00:00  1957  9  1   9  6.4  0.6
2   1957-09-01 12:00:00  1957  9  1  12  5.2  0.4
3   1957-09-01 15:00:00  1957  9  1  15  1.9  0.3
4   1957-09-01 18:00:00  1957  9  1  18  3.7  0.3
5   1957-09-01 21:00:00  1957  9  1  21  3.9  0.4
6   1957-09-02 06:00:00  1957  9  1   6  8.9  0.5
7   1957-09-02 09:00:00  1957  9  1   9  6.4  0.6
8   1957-09-02 12:00:00  1957  9  1  12  5.2  0.4
9   1957-09-02 15:00:00  1957  9  1  15  1.9  0.3
10  1957-09-02 18:00:00  1957  9  1  18  3.7  0.3
11  1957-09-02 21:00:00  1957  9  1  21  3.9  0.4
12  1957-09-03 06:00:00  1957  9  1   6  8.9  0.9
13  1957-09-03 09:00:00  1957  9  1   9  6.4  0.6
14  1957-09-03 12:00:00  1957  9  1  12  5.2  0.4
15  1957-09-03 15:00:00  1957  9  1  15  1.9  0.3
16  1957-09-03 18:00:00  1957  9  1  18  3.7  0.3
17  1957-09-03 21:00:00  1957  9  1  21  3.9  0.4
18  1957-09-04 06:00:00  1957  9  1   6  8.9  0.9
19  1957-09-04 09:00:00  1957  9  1   9  6.4  0.6
20  1957-09-04 12:00:00  1957  9  1  12  5.2  0.4
21  1957-09-04 15:00:00  1957  9  1  15  1.9  0.3
22  1957-09-04 18:00:00  1957  9  1  18  3.7  0.3
23  1957-09-04 21:00:00  1957  9  1  21  3.9  0.4
24  1957-10-01 06:00:00  1957  9  1   6  8.9  0.5
25  1957-10-01 09:00:00  1957  9  1   9  6.4  0.6
26  1957-10-01 12:00:00  1957  9  1  12  5.2  0.4
27  1957-10-01 15:00:00  1957  9  1  15  1.9  0.3
28  1957-10-01 18:00:00  1957  9  1  18  3.7  0.3
29  1957-10-01 21:00:00  1957  9  1  21  3.9  0.4
30  1957-10-02 06:00:00  1957  9  1   6  8.9  0.5
31  1957-10-02 09:00:00  1957  9  1   9  6.4  0.6
32  1957-10-02 12:00:00  1957  9  1  12  5.2  0.4
33  1957-10-02 15:00:00  1957  9  1  15  1.9  0.3
34  1957-10-02 18:00:00  1957  9  1  18  3.7  0.3
35  1957-10-02 21:00:00  1957  9  1  21  3.9  0.4
36  1957-10-03 06:00:00  1957  9  1   6  8.9  0.9
37  1957-10-03 09:00:00  1957  9  1   9  6.4  0.6
38  1957-10-03 12:00:00  1957  9  1  12  5.2  0.4
39  1957-10-03 15:00:00  1957  9  1  15  1.9  0.3
40  1957-10-03 18:00:00  1957  9  1  18  3.7  0.3
41  1957-10-03 21:00:00  1957  9  1  21  3.9  0.4
42  1957-10-04 06:00:00  1957  9  1   6  8.9  0.9
43  1957-10-04 09:00:00  1957  9  1   9  6.4  0.6
44  1957-10-04 12:00:00  1957  9  1  12  5.2  0.4
45  1957-10-04 15:00:00  1957  9  1  15  1.9  0.3
46  1957-10-04 18:00:00  1957  9  1  18  3.7  0.3
47  1957-10-04 21:00:00  1957  9  1  21  3.9  0.4

In [112]:
# Let's format the DT column into a real datetime
df['date'] = pd.to_datetime(df['DT'], format='%Y-%m-%d %H:%M:%S')

# Grouping by 48 hours with a base of 0 (so the start of the grouping window begins midnight - and without a time)
# The max returns the highest number from the HS column.
df_48h = df.groupby(pd.Grouper(key='date', freq='48h', base=0))['HS'].max()
print(df_48h)

date
1957-09-01    0.6
1957-09-03    0.9
1957-09-05    NaN
1957-09-07    NaN
1957-09-09    NaN
1957-09-11    NaN
1957-09-13    NaN
1957-09-15    NaN
1957-09-17    NaN
1957-09-19    NaN
1957-09-21    NaN
1957-09-23    NaN
1957-09-25    NaN
1957-09-27    NaN
1957-09-29    NaN
1957-10-01    0.6
1957-10-03    0.9
Freq: 48H, Name: HS, dtype: float64

In [115]:
# Group all the 'high' values by month and get the mean
df_mm = df_48h.groupby(pd.Grouper(freq='M')).mean()
print(df_mm)

date
1957-09-30    0.75
1957-10-31    0.75
Freq: M, Name: HS, dtype: float64